/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 18:00:31 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.ClienteRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClienteRequest_ESTest extends ClienteRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      clienteRequest0.setTelefone("br.com.marmitaria.rest.request.ClienteRequest");
      String string0 = clienteRequest0.getTelefone();
      assertEquals("br.com.marmitaria.rest.request.ClienteRequest", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      clienteRequest0.setEndereco("br.com.marmitaria.rest.request.ClienteRequest");
      String string0 = clienteRequest0.getEndereco();
      assertEquals("br.com.marmitaria.rest.request.ClienteRequest", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      String string0 = clienteRequest0.getTelefone();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      clienteRequest0.setEndereco("");
      String string0 = clienteRequest0.getEndereco();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      String string0 = clienteRequest0.getEndereco();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ClienteRequest clienteRequest0 = new ClienteRequest();
      clienteRequest0.setTelefone("");
      String string0 = clienteRequest0.getTelefone();
      assertEquals("", string0);
  }
}
