/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:53:06 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.ConfirmacaoDeCodigoRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConfirmacaoDeCodigoRequest_ESTest extends ConfirmacaoDeCodigoRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      confirmacaoDeCodigoRequest0.setEmail("}v)M^By$8)H\"7!Fj");
      String string0 = confirmacaoDeCodigoRequest0.getEmail();
      assertEquals("}v)M^By$8)H\"7!Fj", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      confirmacaoDeCodigoRequest0.setEmail("");
      String string0 = confirmacaoDeCodigoRequest0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      confirmacaoDeCodigoRequest0.setCodigo("Oo6lZl2ykFO");
      String string0 = confirmacaoDeCodigoRequest0.getCodigo();
      assertEquals("Oo6lZl2ykFO", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      confirmacaoDeCodigoRequest0.setCodigo("");
      String string0 = confirmacaoDeCodigoRequest0.getCodigo();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      String string0 = confirmacaoDeCodigoRequest0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ConfirmacaoDeCodigoRequest confirmacaoDeCodigoRequest0 = new ConfirmacaoDeCodigoRequest();
      String string0 = confirmacaoDeCodigoRequest0.getCodigo();
      assertNull(string0);
  }
}
