/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:59:17 GMT 2019
 */

package br.com.marmitaria.persistence.model;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.persistence.model.TipoPagamento;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoPagamento_ESTest extends TipoPagamento_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoPagamento[] tipoPagamentoArray0 = TipoPagamento.values();
      assertEquals(2, tipoPagamentoArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoPagamento tipoPagamento0 = TipoPagamento.valueOf("CARTAO");
      String string0 = tipoPagamento0.getValor();
      assertEquals("Cart\u00E3o", string0);
  }
}
