/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:50:18 GMT 2019
 */

package br.com.marmitaria.persistence.model;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.persistence.model.TipoMarmita;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TipoMarmita_ESTest extends TipoMarmita_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TipoMarmita[] tipoMarmitaArray0 = TipoMarmita.values();
      assertEquals(2, tipoMarmitaArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TipoMarmita tipoMarmita0 = TipoMarmita.valueOf("TRADICIONAL");
      assertEquals("TRADICIONAL", tipoMarmita0.getValor());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TipoMarmita tipoMarmita0 = TipoMarmita.DIVISORIA;
      String string0 = tipoMarmita0.getValor();
      assertEquals("DIVISORIA", string0);
  }
}
