/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:48:58 GMT 2019
 */

package br.com.marmitaria.rest.reponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.marmitaria.persistence.model.Cliente;
import br.com.marmitaria.rest.reponse.ClienteResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ClienteResponse_ESTest extends ClienteResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ClienteResponse clienteResponse0 = null;
      try {
        clienteResponse0 = new ClienteResponse((Cliente) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.marmitaria.rest.reponse.ClienteResponse", e);
      }
  }
}
