/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:50:26 GMT 2019
 */

package br.com.marmitaria.rest.reponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.marmitaria.persistence.model.Produto;
import br.com.marmitaria.rest.reponse.ProdutoResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProdutoResponse_ESTest extends ProdutoResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Produto produto0 = new Produto();
      ProdutoResponse produtoResponse0 = new ProdutoResponse(produto0);
      produtoResponse0.setNome("Nk\"XMwd }&%");
      String string0 = produtoResponse0.getNome();
      assertEquals("Nk\"XMwd }&%", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Produto produto0 = new Produto();
      ProdutoResponse produtoResponse0 = new ProdutoResponse(produto0);
      Long long0 = new Long(0L);
      produtoResponse0.setId(long0);
      Long long1 = produtoResponse0.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProdutoResponse produtoResponse0 = new ProdutoResponse();
      Long long0 = Long.getLong("br.com.marmitaria.rest.reponse.ProdutoResponse", (-371L));
      produtoResponse0.setId(long0);
      Long long1 = produtoResponse0.getId();
      assertEquals((-371L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProdutoResponse produtoResponse0 = new ProdutoResponse();
      produtoResponse0.setNome("");
      String string0 = produtoResponse0.getNome();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProdutoResponse produtoResponse0 = new ProdutoResponse();
      Long long0 = produtoResponse0.getId();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProdutoResponse produtoResponse0 = new ProdutoResponse();
      String string0 = produtoResponse0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ProdutoResponse produtoResponse0 = null;
      try {
        produtoResponse0 = new ProdutoResponse((Produto) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.marmitaria.rest.reponse.ProdutoResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ProdutoResponse produtoResponse0 = new ProdutoResponse();
      Long long0 = Long.valueOf(1L);
      produtoResponse0.setId(long0);
      Long long1 = produtoResponse0.getId();
      assertEquals(1L, (long)long1);
  }
}
