/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:52:58 GMT 2019
 */

package br.com.marmitaria.rest.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.marmitaria.persistence.model.Usuario;
import br.com.marmitaria.rest.util.Email;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Email_ESTest extends Email_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      Email email0 = new Email(usuario0);
      String string0 = email0.getHtmlConfirmarEmail();
      assertEquals("<!doctype html>\n<html lang=\"pt-br\">\n  <head>\n    <meta charset=\"utf-8\">\n  </head>\n  <body>\n    <div>\n        <div >\n          <h2>Fulano de sal</h2>\n        </div>\n        <div>\n          <h5>Confirma\u00E7\u00E3o de cadastro</h5>\n          <p>Recebemos uma solicita\u00E7\u00E3o de cadastro no sistema, clique no link abaixo para confirmar seu cadastro.</p>\n          <a href=\"http://null/api/publico/cliente/confirmacao?id=null\">Confirmar</a>\n        </div>\n    </div>\n  </body>\n</html>", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Email email0 = new Email((Usuario) null);
      // Undeclared exception!
      try { 
        email0.enviaConfirmaEmail();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.marmitaria.rest.util.Email", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Email email0 = new Email((Usuario) null);
      // Undeclared exception!
      try { 
        email0.getHtmlConfirmarEmail();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("br.com.marmitaria.rest.util.Email", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Email email0 = new Email((Usuario) null);
      String string0 = email0.getHtmlrecuperarSenha("Q{%O[s$G50Y");
      assertEquals("<!doctype html>\n<html lang=\"pt-br\">\n  <head>\n    <meta charset=\"utf-8\">\n  </head>\n  <body>\n    <div>\n        <div >\n          <h2>Fulano de sal</h2>\n        </div>\n        <div>\n          <h5>Confirma\u00E7\u00E3o de Recupera\u00E7\u00E3o de senha</h5>\n          <p>Recebemos uma solicita\u00E7\u00E3o de recupera\u00E7\u00E3o de senha, seu c\u00F3digo de verifica\u00E7\u00E3o \u00E9: <h2><b>Q{%O[s$G50Y</b></h2>.</p>\n        </div>\n    </div>\n  </body>\n</html>", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      Email email0 = new Email(usuario0);
      String string0 = email0.getSubject();
      assertEquals("Confirma\u00E7\u00E3o de cadastro", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      Email email0 = new Email(usuario0);
      email0.enviaCodigoRecuperacao("Confirma\u00E7\u00E3o de cadastro");
      assertEquals("Confirma\u00E7\u00E3o de cadastro", email0.getSubject());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      Email email0 = new Email(usuario0);
      email0.setUsuario(usuario0);
      assertNull(usuario0.getSenha());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Usuario usuario0 = new Usuario();
      Email email0 = new Email(usuario0);
      email0.enviaConfirmaEmail();
      assertEquals("Confirma\u00E7\u00E3o de cadastro", email0.getSubject());
  }
}
