/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:58:33 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.CategoriaRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CategoriaRequest_ESTest extends CategoriaRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      Long long0 = new Long(859L);
      categoriaRequest0.setId(long0);
      Long long1 = categoriaRequest0.getId();
      assertEquals(859L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      Long long0 = new Long((-1L));
      categoriaRequest0.setId(long0);
      Long long1 = categoriaRequest0.getId();
      assertEquals((-1L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      categoriaRequest0.setDescricao("br.com.marmitaria.rest.request.CategoriaRequest");
      String string0 = categoriaRequest0.getDescricao();
      assertEquals("br.com.marmitaria.rest.request.CategoriaRequest", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      categoriaRequest0.setDescricao("");
      String string0 = categoriaRequest0.getDescricao();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      Long long0 = new Long(0L);
      categoriaRequest0.setId(long0);
      Long long1 = categoriaRequest0.getId();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      String string0 = categoriaRequest0.getDescricao();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CategoriaRequest categoriaRequest0 = new CategoriaRequest();
      Long long0 = categoriaRequest0.getId();
      assertNull(long0);
  }
}
