/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:58:14 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.LoginRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoginRequest_ESTest extends LoginRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      loginRequest0.setSenha("");
      String string0 = loginRequest0.getSenha();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      loginRequest0.setEmail("2HL");
      String string0 = loginRequest0.getEmail();
      assertEquals("2HL", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      String string0 = loginRequest0.getSenha();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      loginRequest0.setSenha("Mz`");
      String string0 = loginRequest0.getSenha();
      assertEquals("Mz`", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      loginRequest0.setEmail("");
      String string0 = loginRequest0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LoginRequest loginRequest0 = new LoginRequest();
      String string0 = loginRequest0.getEmail();
      assertNull(string0);
  }
}
