/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 18:00:13 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.ProdutoRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProdutoRequest_ESTest extends ProdutoRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      produtoRequest0.setNome("br.com.marmitaria.rest.request.ProdutoRequest");
      String string0 = produtoRequest0.getNome();
      assertEquals("br.com.marmitaria.rest.request.ProdutoRequest", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = new Long(0L);
      produtoRequest0.setIdProduto(long0);
      Long long1 = produtoRequest0.getIdProduto();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = Long.valueOf(684L);
      produtoRequest0.setIdProduto(long0);
      Long long1 = produtoRequest0.getIdProduto();
      assertEquals(684L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = new Long(4295L);
      produtoRequest0.setIdCategoria(long0);
      Long long1 = produtoRequest0.getIdCategoria();
      assertEquals(4295L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = new Long(0L);
      produtoRequest0.setIdCategoria(long0);
      Long long1 = produtoRequest0.getIdCategoria();
      assertEquals(0L, (long)long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = new Long((-3498L));
      produtoRequest0.setIdCategoria(long0);
      Long long1 = produtoRequest0.getIdCategoria();
      assertEquals((-3498L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = produtoRequest0.getIdCategoria();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = produtoRequest0.getIdProduto();
      assertNull(long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      Long long0 = new Long((-454L));
      produtoRequest0.setIdProduto(long0);
      Long long1 = produtoRequest0.getIdProduto();
      assertEquals((-454L), (long)long1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      String string0 = produtoRequest0.getNome();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProdutoRequest produtoRequest0 = new ProdutoRequest();
      produtoRequest0.setNome("");
      String string0 = produtoRequest0.getNome();
      assertEquals("", string0);
  }
}
