/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:49:41 GMT 2019
 */

package br.com.marmitaria.rest.request;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.request.RecuperacaoRequest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RecuperacaoRequest_ESTest extends RecuperacaoRequest_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      recuperacaoRequest0.setSenha("el-V/J_&");
      String string0 = recuperacaoRequest0.getSenha();
      assertEquals("el-V/J_&", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      recuperacaoRequest0.setEmail("DVPzp");
      String string0 = recuperacaoRequest0.getEmail();
      assertEquals("DVPzp", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      recuperacaoRequest0.setSenha("");
      String string0 = recuperacaoRequest0.getSenha();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      String string0 = recuperacaoRequest0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      String string0 = recuperacaoRequest0.getSenha();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RecuperacaoRequest recuperacaoRequest0 = new RecuperacaoRequest();
      recuperacaoRequest0.setEmail("");
      String string0 = recuperacaoRequest0.getEmail();
      assertEquals("", string0);
  }
}
