/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:51:03 GMT 2019
 */

package br.com.marmitaria.rest.login;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.login.TokenKey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenKey_ESTest extends TokenKey_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TokenKey[] tokenKeyArray0 = TokenKey.values();
      assertEquals(2, tokenKeyArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TokenKey tokenKey0 = TokenKey.valueOf("TOKEN_RECUPERAR_SENHA");
      assertEquals("chevededescriptografiadotokenderecuperarsenha", tokenKey0.getValue());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TokenKey tokenKey0 = TokenKey.TOKEN_RECUPERAR_SENHA;
      String string0 = tokenKey0.getValue();
      assertEquals("chevededescriptografiadotokenderecuperarsenha", string0);
  }
}
