/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:51:57 GMT 2019
 */

package br.com.marmitaria.rest.exception.usuario;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.exception.usuario.EmailNaoCadastradoException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailNaoCadastradoException_ESTest extends EmailNaoCadastradoException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EmailNaoCadastradoException emailNaoCadastradoException0 = new EmailNaoCadastradoException();
  }
}
