/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 17:54:11 GMT 2019
 */

package br.com.marmitaria.rest.exception.usuario;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.marmitaria.rest.exception.usuario.SenhaInvalidaException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SenhaInvalidaException_ESTest extends SenhaInvalidaException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SenhaInvalidaException senhaInvalidaException0 = new SenhaInvalidaException();
  }
}
